spring.application.name=mhv

# ===============================
# JWT & SECURITY
# ===============================
jwt.secret=QWJjZDEyMzQ1Njc4OTBBYmNkMTIzNDU2Nzg5MEFiY2QxMjM0NTY3ODkwQWJjZA==
jwt.expiration-ms=86400000

# ===============================
# CORS
# ===============================
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173,http://localhost:3000,http://127.0.0.1:3000,http://192.168.*.*:*,https://*.ngrok-free.dev,https://*.ngrok-free.app,https://*.vercel.app,https://mhv-5wgsdgk92-minhtvpy00202-gits-projects.vercel.app,https://mhv.vercel.app

# ===============================
# AZURE SQL DATABASE
# ===============================
spring.datasource.url=jdbc:sqlserver://mhv-server.database.windows.net:1433;database=mhv_db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
spring.datasource.username=mhv
spring.datasource.password=Minh@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# HIBERNATE
# ===============================
# Auto create/update tables for empty Azure DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# SERVER COMPRESSION
# ===============================
server.compression.enabled=true
server.compression.mime-types=application/json,text/plain,text/html,text/css,application/javascript,application/xml,text/xml
server.compression.min-response-size=1024

# ===============================
# FILE UPLOAD
# ===============================
app.upload-dir=uploads
